name: DeployApp
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "highlander.44@gmail.com"
        git config --global user.name "johncokos"
        git remote set-url origin https://3b87ba7a879eb7cdae04d4dede2bf2b133c2aae1@github.com/codefellows/dsa-practice.git
        npm run deploy
